[package]
name = "substrate-subxt"
version = "0.4.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "GPL-3.0"
readme = "README.md"
description = "Submit extrinsics (transactions) to a substrate node via RPC"
keywords = ["parity", "substrate", "blockchain"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
log = "0.4"
thiserror = "1.0"
futures = "0.3"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee/", features = ["ws"] }
num-traits = { version = "0.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "1.7"
codec = { package = "parity-scale-codec", version = "1.1", default-features = false, features = ["derive", "full"] }

frame-metadata = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "frame-metadata" }
frame-support = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "frame-support" }
sp-runtime = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "sp-runtime" }
sp-version = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "sp-version" }
pallet-indices = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "pallet-indices" }
hex = "0.4.0"
sc-rpc-api = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "sc-rpc-api" }
sp-rpc = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "sp-rpc" }
sp-core = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "sp-core" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "sp-transaction-pool" }

[dev-dependencies]
async-std = "1.2.0"
env_logger = "0.7"
wabt = "0.9"
frame-system = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "frame-system" }
node-runtime = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "node-runtime" }
pallet-balances = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "pallet-balances" }
sp-keyring = { git = "https://github.com/paritytech/substrate/", rev = "de2ffd937db78093efaa58d7cc08f5599a8f4728", package = "sp-keyring" }
